set_property SRC_FILE_INFO {cfile:F:/Demo/Demo.srcs/constrs_1/new/setting.xdc rfile:../../../Demo.srcs/constrs_1/new/setting.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E13 [get_ports PL_LED_G]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E12 [get_ports PL_LED_R]
