# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/.Xil/Vivado-2996-DESKTOP-O25IKCM/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z007sclg225-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    f:/Git_Fpga/FPGA_Starter/Project/LiveCamera/LiveCamera.srcs/sources_1/bd/OV7670_QVGA/ipshared/c923
    f:/Git_Fpga/FPGA_Starter/Project/LiveCamera/LiveCamera.srcs/sources_1/bd/OV7670_QVGA/ipshared/ec67/hdl
  } {
      C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    f:/Git_Fpga/FPGA_Starter/Project/LiveCamera/LiveCamera.srcs/sources_1/bd/OV7670_QVGA/ipshared/c923
    f:/Git_Fpga/FPGA_Starter/Project/LiveCamera/LiveCamera.srcs/sources_1/bd/OV7670_QVGA/ipshared/ec67/hdl
  } {
      F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/.Xil/Vivado-2996-DESKTOP-O25IKCM/realtime/OV7670_QVGA_Address_Generator_0_0_stub.v
      F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/.Xil/Vivado-2996-DESKTOP-O25IKCM/realtime/OV7670_QVGA_RGB_0_0_stub.v
      F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/.Xil/Vivado-2996-DESKTOP-O25IKCM/realtime/OV7670_QVGA_VGA_0_0_stub.v
      F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/.Xil/Vivado-2996-DESKTOP-O25IKCM/realtime/OV7670_QVGA_axi_gpio_0_0_stub.v
      F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/.Xil/Vivado-2996-DESKTOP-O25IKCM/realtime/OV7670_QVGA_axi_uartlite_0_0_stub.v
      F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/.Xil/Vivado-2996-DESKTOP-O25IKCM/realtime/OV7670_QVGA_blk_mem_gen_0_0_stub.v
      F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/.Xil/Vivado-2996-DESKTOP-O25IKCM/realtime/OV7670_QVGA_clk_wiz_0_0_stub.v
      F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/.Xil/Vivado-2996-DESKTOP-O25IKCM/realtime/OV7670_QVGA_debounce_0_0_stub.v
      F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/.Xil/Vivado-2996-DESKTOP-O25IKCM/realtime/OV7670_QVGA_ov7670_capture_0_0_stub.v
      F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/.Xil/Vivado-2996-DESKTOP-O25IKCM/realtime/OV7670_QVGA_ov7670_controller_0_0_stub.v
      F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/.Xil/Vivado-2996-DESKTOP-O25IKCM/realtime/OV7670_QVGA_processing_system7_0_0_stub.v
      F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/.Xil/Vivado-2996-DESKTOP-O25IKCM/realtime/OV7670_QVGA_xbar_0_stub.v
      F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/.Xil/Vivado-2996-DESKTOP-O25IKCM/realtime/OV7670_QVGA_rst_ps7_0_50M_0_stub.v
      F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/.Xil/Vivado-2996-DESKTOP-O25IKCM/realtime/OV7670_QVGA_auto_pc_0_stub.v
      f:/Git_Fpga/FPGA_Starter/Project/LiveCamera/LiveCamera.srcs/sources_1/bd/OV7670_QVGA/ipshared/66e7/hdl/xlconstant_v1_1_vl_rfs.v
      f:/Git_Fpga/FPGA_Starter/Project/LiveCamera/LiveCamera.srcs/sources_1/bd/OV7670_QVGA/ip/OV7670_QVGA_xlconstant_0_0/synth/OV7670_QVGA_xlconstant_0_0.v
      f:/Git_Fpga/FPGA_Starter/Project/LiveCamera/LiveCamera.srcs/sources_1/bd/OV7670_QVGA/ip/OV7670_QVGA_xlconstant_1_0/synth/OV7670_QVGA_xlconstant_1_0.v
      F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/LiveCamera.srcs/sources_1/bd/OV7670_QVGA/synth/OV7670_QVGA.v
      F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/LiveCamera.srcs/sources_1/bd/OV7670_QVGA/hdl/OV7670_QVGA_wrapper.v
    }
      rt::read_vhdl -lib xil_defaultlib {
      F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/LiveCamera.srcs/sources_1/imports/Downloads/address_generator_vhd.vhd
      F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/LiveCamera.srcs/sources_1/imports/Downloads/vga_vhd.vhd
      F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/LiveCamera.srcs/sources_1/imports/Downloads/vga.vhd
      F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/LiveCamera.srcs/sources_1/imports/Downloads/debounce_vhd.vhd
      F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/LiveCamera.srcs/sources_1/imports/Downloads/ov7670_capture_vhd.vhd
      F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/LiveCamera.srcs/sources_1/imports/Downloads/i3c2_vhd.vhd
      F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/LiveCamera.srcs/sources_1/imports/Downloads/ov7670_controller_vhd.vhd
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top OV7670_QVGA_wrapper
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/.Xil/Vivado-2996-DESKTOP-O25IKCM/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
