# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Fpga/minized_pins.xdc

# Block Designs: bd/OV7670_QVGA/OV7670_QVGA.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV7670_QVGA || ORIG_REF_NAME==OV7670_QVGA} -quiet] -quiet

# IP: bd/OV7670_QVGA/ip/OV7670_QVGA_Address_Generator_0_0/OV7670_QVGA_Address_Generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV7670_QVGA_Address_Generator_0_0 || ORIG_REF_NAME==OV7670_QVGA_Address_Generator_0_0} -quiet] -quiet

# IP: bd/OV7670_QVGA/ip/OV7670_QVGA_RGB_0_0/OV7670_QVGA_RGB_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV7670_QVGA_RGB_0_0 || ORIG_REF_NAME==OV7670_QVGA_RGB_0_0} -quiet] -quiet

# IP: bd/OV7670_QVGA/ip/OV7670_QVGA_VGA_0_0/OV7670_QVGA_VGA_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV7670_QVGA_VGA_0_0 || ORIG_REF_NAME==OV7670_QVGA_VGA_0_0} -quiet] -quiet

# IP: bd/OV7670_QVGA/ip/OV7670_QVGA_blk_mem_gen_0_0/OV7670_QVGA_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV7670_QVGA_blk_mem_gen_0_0 || ORIG_REF_NAME==OV7670_QVGA_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/OV7670_QVGA/ip/OV7670_QVGA_clk_wiz_0_0/OV7670_QVGA_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV7670_QVGA_clk_wiz_0_0 || ORIG_REF_NAME==OV7670_QVGA_clk_wiz_0_0} -quiet] -quiet

# IP: bd/OV7670_QVGA/ip/OV7670_QVGA_debounce_0_0/OV7670_QVGA_debounce_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV7670_QVGA_debounce_0_0 || ORIG_REF_NAME==OV7670_QVGA_debounce_0_0} -quiet] -quiet

# IP: bd/OV7670_QVGA/ip/OV7670_QVGA_ov7670_capture_0_0/OV7670_QVGA_ov7670_capture_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV7670_QVGA_ov7670_capture_0_0 || ORIG_REF_NAME==OV7670_QVGA_ov7670_capture_0_0} -quiet] -quiet

# IP: bd/OV7670_QVGA/ip/OV7670_QVGA_ov7670_controller_0_0/OV7670_QVGA_ov7670_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV7670_QVGA_ov7670_controller_0_0 || ORIG_REF_NAME==OV7670_QVGA_ov7670_controller_0_0} -quiet] -quiet

# IP: bd/OV7670_QVGA/ip/OV7670_QVGA_processing_system7_0_0/OV7670_QVGA_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV7670_QVGA_processing_system7_0_0 || ORIG_REF_NAME==OV7670_QVGA_processing_system7_0_0} -quiet] -quiet

# IP: bd/OV7670_QVGA/ip/OV7670_QVGA_rst_ps7_0_50M_0/OV7670_QVGA_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV7670_QVGA_rst_ps7_0_50M_0 || ORIG_REF_NAME==OV7670_QVGA_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/OV7670_QVGA/ip/OV7670_QVGA_xlconstant_0_0/OV7670_QVGA_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV7670_QVGA_xlconstant_0_0 || ORIG_REF_NAME==OV7670_QVGA_xlconstant_0_0} -quiet] -quiet

# IP: bd/OV7670_QVGA/ip/OV7670_QVGA_xlconstant_1_0/OV7670_QVGA_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV7670_QVGA_xlconstant_1_0 || ORIG_REF_NAME==OV7670_QVGA_xlconstant_1_0} -quiet] -quiet

# IP: bd/OV7670_QVGA/ip/OV7670_QVGA_axi_iic_0_0/OV7670_QVGA_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV7670_QVGA_axi_iic_0_0 || ORIG_REF_NAME==OV7670_QVGA_axi_iic_0_0} -quiet] -quiet

# IP: bd/OV7670_QVGA/ip/OV7670_QVGA_ps7_0_axi_periph_0/OV7670_QVGA_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV7670_QVGA_ps7_0_axi_periph_0 || ORIG_REF_NAME==OV7670_QVGA_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/OV7670_QVGA/ip/OV7670_QVGA_auto_pc_0/OV7670_QVGA_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV7670_QVGA_auto_pc_0 || ORIG_REF_NAME==OV7670_QVGA_auto_pc_0} -quiet] -quiet

# XDC: bd/OV7670_QVGA/OV7670_QVGA_ooc.xdc
