# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/setting.xdc

# Block Designs: bd/Demo/Demo.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo || ORIG_REF_NAME==Demo} -quiet] -quiet

# IP: bd/Demo/ip/Demo_PwmIp_Demo_0_1/Demo_PwmIp_Demo_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_PwmIp_Demo_0_1 || ORIG_REF_NAME==Demo_PwmIp_Demo_0_1} -quiet] -quiet

# IP: bd/Demo/ip/Demo_processing_system7_0_0/Demo_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_processing_system7_0_0 || ORIG_REF_NAME==Demo_processing_system7_0_0} -quiet] -quiet

# IP: bd/Demo/ip/Demo_ps7_0_axi_periph_1/Demo_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_ps7_0_axi_periph_1 || ORIG_REF_NAME==Demo_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/Demo/ip/Demo_rst_ps7_0_50M_2/Demo_rst_ps7_0_50M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_rst_ps7_0_50M_2 || ORIG_REF_NAME==Demo_rst_ps7_0_50M_2} -quiet] -quiet

# IP: bd/Demo/ip/Demo_util_reduced_logic_0_0/Demo_util_reduced_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_util_reduced_logic_0_0 || ORIG_REF_NAME==Demo_util_reduced_logic_0_0} -quiet] -quiet

# IP: bd/Demo/ip/Demo_auto_pc_0/Demo_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Demo_auto_pc_0 || ORIG_REF_NAME==Demo_auto_pc_0} -quiet] -quiet

# XDC: bd/Demo/Demo_ooc.xdc
