
####################################################################################
# Generated by Vivado 2019.1 built on 'Fri May 24 14:49:42 MDT 2019' by 'xbuild'
# Command Used: write_xdc -force F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/constrs_1.xdc
####################################################################################


####################################################################################
# Constraints from file : 'OV7670_QVGA_clk_wiz_0_0_board.xdc'
####################################################################################

#--------------------Physical Constraints-----------------



####################################################################################
# Constraints from file : 'OV7670_QVGA_clk_wiz_0_0.xdc'
####################################################################################


# file: OV7670_QVGA_clk_wiz_0_0.xdc
#
# (c) Copyright 2008 - 2013 Xilinx, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of Xilinx, Inc. and is protected under U.S. and
# international copyright and other intellectual property
# laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# Xilinx, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) Xilinx shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or Xilinx had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# Xilinx products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of Xilinx products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.
#

# Input clock periods. These duplicate the values entered for the
# input clocks. You can use these to time your system. If required
# commented constraints can be used in the top level xdc
#----------------------------------------------------------------
# Connect to input port when clock capable pin is selected for input
current_instance OV7670_QVGA_i/clk_wiz_0/inst
create_clock -period 10.000 [get_ports -scoped_to_current_instance clk_in1]
set_input_jitter [get_clocks -of_objects [get_ports -scoped_to_current_instance clk_in1]] 0.100


set_property PHASESHIFT_MODE WAVEFORM [get_cells -hierarchical *adv*]


####################################################################################
# Constraints from file : 'OV7670_QVGA_processing_system7_0_0.xdc'
####################################################################################

############################################################################
##
##  Xilinx, Inc. 2006            www.xilinx.com
############################################################################
##  File name :       ps7_constraints.xdc
##
##  Details :     Constraints file
##                    FPGA family:       zynq
##                    FPGA:              xc7z007sclg225-1
##                    Device Size:        xc7z007s
##                    Package:            clg225
##                    Speedgrade:         -1
##
##
############################################################################
############################################################################
############################################################################
# Clock constraints                                                        #
############################################################################
current_instance -quiet
current_instance OV7670_QVGA_i/processing_system7_0/inst
create_clock -period 20.000 -name clk_fpga_0 [get_pins {PS7_i/FCLKCLK[0]}]
set_input_jitter clk_fpga_0 0.600
#The clocks are asynchronous, user should constrain them appropriately.#
create_clock -period 10.000 -name clk_fpga_1 [get_pins {PS7_i/FCLKCLK[1]}]
set_input_jitter clk_fpga_1 0.300
#The clocks are asynchronous, user should constrain them appropriately.#


############################################################################
# I/O STANDARDS and Location Constraints                                   #
############################################################################

#  GPIO / gpio[53] / MIO[53]
current_instance -quiet
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[31]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[31]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[31]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[31]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[31]}]
#  GPIO / gpio[52] / MIO[52]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[30]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[30]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[30]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[30]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[30]}]
#  UART 1 / rx / MIO[49]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[29]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[29]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[29]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[29]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[29]}]
#  UART 1 / tx / MIO[48]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[28]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[28]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[28]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[28]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[28]}]
#  USB 0 / data[7] / MIO[39]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[27]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[27]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[27]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[27]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[27]}]
#  USB 0 / data[6] / MIO[38]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[26]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[26]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[26]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[26]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[26]}]
#  USB 0 / data[5] / MIO[37]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[25]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[25]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[25]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[25]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[25]}]
#  USB 0 / clk / MIO[36]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[24]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[24]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[24]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[24]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[24]}]
#  USB 0 / data[3] / MIO[35]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[23]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[23]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[23]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[23]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[23]}]
#  USB 0 / data[2] / MIO[34]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[22]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[22]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[22]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[22]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[22]}]
#  USB 0 / data[1] / MIO[33]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[21]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[21]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[21]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[21]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[21]}]
#  USB 0 / data[0] / MIO[32]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[20]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[20]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[20]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[20]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[20]}]
#  USB 0 / nxt / MIO[31]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[19]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[19]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[19]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[19]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[19]}]
#  USB 0 / stp / MIO[30]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[18]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[18]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[18]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[18]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[18]}]
#  USB 0 / dir / MIO[29]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[17]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[17]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[17]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[17]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[17]}]
#  USB 0 / data[4] / MIO[28]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[16]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[16]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[16]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[16]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[16]}]
#  SD 1 / data[3] / MIO[15]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[15]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[15]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[15]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[15]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[15]}]
#  SD 1 / data[2] / MIO[14]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[14]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[14]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[14]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[14]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[14]}]
#  SD 1 / data[1] / MIO[13]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[13]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[13]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[13]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[13]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[13]}]
#  SD 1 / clk / MIO[12]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[12]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[12]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[12]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[12]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[12]}]
#  SD 1 / cmd / MIO[11]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[11]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[11]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[11]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[11]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[11]}]
#  SD 1 / data[0] / MIO[10]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[10]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[10]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[10]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[10]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[10]}]
#  GPIO / gpio[9] / MIO[9]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[9]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[9]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[9]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[9]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[9]}]
#  Quad SPI Flash / qspi_fbclk / MIO[8]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[8]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[8]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[8]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[8]}]
#  USB Reset / reset / MIO[7]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[7]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[7]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[7]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[7]}]
#  Quad SPI Flash / qspi0_sclk / MIO[6]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[6]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[6]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[6]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[6]}]
#  Quad SPI Flash / qspi0_io[3]/HOLD_B / MIO[5]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[5]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[5]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[5]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[5]}]
#  Quad SPI Flash / qspi0_io[2] / MIO[4]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[4]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[4]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[4]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[4]}]
#  Quad SPI Flash / qspi0_io[1] / MIO[3]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[3]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[3]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[3]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[3]}]
#  Quad SPI Flash / qspi0_io[0] / MIO[2]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[2]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[2]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[2]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[2]}]
#  Quad SPI Flash / qspi0_ss_b / MIO[1]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[1]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[1]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[1]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[1]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[1]}]
#  GPIO / gpio[0] / MIO[0]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[0]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[0]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[0]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[0]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[0]}]
set_property IOSTANDARD SSTL135_T_DCI [get_ports FIXED_IO_ddr_vrp]
set_property SLEW FAST [get_ports FIXED_IO_ddr_vrp]
set_property PIO_DIRECTION BIDIR [get_ports FIXED_IO_ddr_vrp]
set_property IOSTANDARD SSTL135_T_DCI [get_ports FIXED_IO_ddr_vrn]
set_property SLEW FAST [get_ports FIXED_IO_ddr_vrn]
set_property PIO_DIRECTION BIDIR [get_ports FIXED_IO_ddr_vrn]
set_property IOSTANDARD SSTL135 [get_ports DDR_we_n]
set_property SLEW SLOW [get_ports DDR_we_n]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_we_n]
set_property IOSTANDARD SSTL135 [get_ports DDR_ras_n]
set_property SLEW SLOW [get_ports DDR_ras_n]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_ras_n]
set_property IOSTANDARD SSTL135 [get_ports DDR_odt]
set_property SLEW SLOW [get_ports DDR_odt]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_odt]
set_property IOSTANDARD SSTL135 [get_ports DDR_reset_n]
set_property SLEW FAST [get_ports DDR_reset_n]
set_property PIO_DIRECTION BIDIR [get_ports DDR_reset_n]
set_property IOSTANDARD DIFF_SSTL135_T_DCI [get_ports {DDR_dqs_p[1]}]
set_property SLEW FAST [get_ports {DDR_dqs_p[1]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_p[1]}]
set_property IOSTANDARD DIFF_SSTL135_T_DCI [get_ports {DDR_dqs_p[0]}]
set_property SLEW FAST [get_ports {DDR_dqs_p[0]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_p[0]}]
set_property IOSTANDARD DIFF_SSTL135_T_DCI [get_ports {DDR_dqs_n[1]}]
set_property SLEW FAST [get_ports {DDR_dqs_n[1]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_n[1]}]
set_property IOSTANDARD DIFF_SSTL135_T_DCI [get_ports {DDR_dqs_n[0]}]
set_property SLEW FAST [get_ports {DDR_dqs_n[0]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_n[0]}]
set_property IOSTANDARD SSTL135_T_DCI [get_ports {DDR_dq[9]}]
set_property SLEW FAST [get_ports {DDR_dq[9]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[9]}]
set_property IOSTANDARD SSTL135_T_DCI [get_ports {DDR_dq[8]}]
set_property SLEW FAST [get_ports {DDR_dq[8]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[8]}]
set_property IOSTANDARD SSTL135_T_DCI [get_ports {DDR_dq[7]}]
set_property SLEW FAST [get_ports {DDR_dq[7]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[7]}]
set_property IOSTANDARD SSTL135_T_DCI [get_ports {DDR_dq[6]}]
set_property SLEW FAST [get_ports {DDR_dq[6]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[6]}]
set_property IOSTANDARD SSTL135_T_DCI [get_ports {DDR_dq[5]}]
set_property SLEW FAST [get_ports {DDR_dq[5]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[5]}]
set_property IOSTANDARD SSTL135_T_DCI [get_ports {DDR_dq[4]}]
set_property SLEW FAST [get_ports {DDR_dq[4]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[4]}]
set_property IOSTANDARD SSTL135_T_DCI [get_ports {DDR_dq[3]}]
set_property SLEW FAST [get_ports {DDR_dq[3]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[3]}]
set_property IOSTANDARD SSTL135_T_DCI [get_ports {DDR_dq[2]}]
set_property SLEW FAST [get_ports {DDR_dq[2]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[2]}]
set_property IOSTANDARD SSTL135_T_DCI [get_ports {DDR_dq[1]}]
set_property SLEW FAST [get_ports {DDR_dq[1]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[1]}]
set_property IOSTANDARD SSTL135_T_DCI [get_ports {DDR_dq[15]}]
set_property SLEW FAST [get_ports {DDR_dq[15]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[15]}]
set_property IOSTANDARD SSTL135_T_DCI [get_ports {DDR_dq[14]}]
set_property SLEW FAST [get_ports {DDR_dq[14]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[14]}]
set_property IOSTANDARD SSTL135_T_DCI [get_ports {DDR_dq[13]}]
set_property SLEW FAST [get_ports {DDR_dq[13]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[13]}]
set_property IOSTANDARD SSTL135_T_DCI [get_ports {DDR_dq[12]}]
set_property SLEW FAST [get_ports {DDR_dq[12]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[12]}]
set_property IOSTANDARD SSTL135_T_DCI [get_ports {DDR_dq[11]}]
set_property SLEW FAST [get_ports {DDR_dq[11]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[11]}]
set_property IOSTANDARD SSTL135_T_DCI [get_ports {DDR_dq[10]}]
set_property SLEW FAST [get_ports {DDR_dq[10]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[10]}]
set_property IOSTANDARD SSTL135_T_DCI [get_ports {DDR_dq[0]}]
set_property SLEW FAST [get_ports {DDR_dq[0]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[0]}]
set_property IOSTANDARD SSTL135_T_DCI [get_ports {DDR_dm[1]}]
set_property SLEW FAST [get_ports {DDR_dm[1]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dm[1]}]
set_property IOSTANDARD SSTL135_T_DCI [get_ports {DDR_dm[0]}]
set_property SLEW FAST [get_ports {DDR_dm[0]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dm[0]}]
set_property IOSTANDARD SSTL135 [get_ports DDR_cs_n]
set_property SLEW SLOW [get_ports DDR_cs_n]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_cs_n]
set_property IOSTANDARD SSTL135 [get_ports DDR_cke]
set_property SLEW SLOW [get_ports DDR_cke]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_cke]
set_property IOSTANDARD DIFF_SSTL135 [get_ports DDR_ck_p]
set_property SLEW FAST [get_ports DDR_ck_p]
set_property PIO_DIRECTION INPUT [get_ports DDR_ck_p]
set_property IOSTANDARD DIFF_SSTL135 [get_ports DDR_ck_n]
set_property SLEW FAST [get_ports DDR_ck_n]
set_property PIO_DIRECTION INPUT [get_ports DDR_ck_n]
set_property IOSTANDARD SSTL135 [get_ports DDR_cas_n]
set_property SLEW SLOW [get_ports DDR_cas_n]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_cas_n]
set_property IOSTANDARD SSTL135 [get_ports {DDR_ba[2]}]
set_property SLEW SLOW [get_ports {DDR_ba[2]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_ba[2]}]
set_property IOSTANDARD SSTL135 [get_ports {DDR_ba[1]}]
set_property SLEW SLOW [get_ports {DDR_ba[1]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_ba[1]}]
set_property IOSTANDARD SSTL135 [get_ports {DDR_ba[0]}]
set_property SLEW SLOW [get_ports {DDR_ba[0]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_ba[0]}]
set_property IOSTANDARD SSTL135 [get_ports {DDR_addr[9]}]
set_property SLEW SLOW [get_ports {DDR_addr[9]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[9]}]
set_property IOSTANDARD SSTL135 [get_ports {DDR_addr[8]}]
set_property SLEW SLOW [get_ports {DDR_addr[8]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[8]}]
set_property IOSTANDARD SSTL135 [get_ports {DDR_addr[7]}]
set_property SLEW SLOW [get_ports {DDR_addr[7]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[7]}]
set_property IOSTANDARD SSTL135 [get_ports {DDR_addr[6]}]
set_property SLEW SLOW [get_ports {DDR_addr[6]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[6]}]
set_property IOSTANDARD SSTL135 [get_ports {DDR_addr[5]}]
set_property SLEW SLOW [get_ports {DDR_addr[5]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[5]}]
set_property IOSTANDARD SSTL135 [get_ports {DDR_addr[4]}]
set_property SLEW SLOW [get_ports {DDR_addr[4]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[4]}]
set_property IOSTANDARD SSTL135 [get_ports {DDR_addr[3]}]
set_property SLEW SLOW [get_ports {DDR_addr[3]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[3]}]
set_property IOSTANDARD SSTL135 [get_ports {DDR_addr[2]}]
set_property SLEW SLOW [get_ports {DDR_addr[2]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[2]}]
set_property IOSTANDARD SSTL135 [get_ports {DDR_addr[1]}]
set_property SLEW SLOW [get_ports {DDR_addr[1]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[1]}]
set_property IOSTANDARD SSTL135 [get_ports {DDR_addr[14]}]
set_property SLEW SLOW [get_ports {DDR_addr[14]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[14]}]
set_property IOSTANDARD SSTL135 [get_ports {DDR_addr[13]}]
set_property SLEW SLOW [get_ports {DDR_addr[13]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[13]}]
set_property IOSTANDARD SSTL135 [get_ports {DDR_addr[12]}]
set_property SLEW SLOW [get_ports {DDR_addr[12]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[12]}]
set_property IOSTANDARD SSTL135 [get_ports {DDR_addr[11]}]
set_property SLEW SLOW [get_ports {DDR_addr[11]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[11]}]
set_property IOSTANDARD SSTL135 [get_ports {DDR_addr[10]}]
set_property SLEW SLOW [get_ports {DDR_addr[10]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[10]}]
set_property IOSTANDARD SSTL135 [get_ports {DDR_addr[0]}]
set_property SLEW SLOW [get_ports {DDR_addr[0]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports FIXED_IO_ps_porb]
set_property SLEW FAST [get_ports FIXED_IO_ps_porb]
set_property IOSTANDARD LVCMOS33 [get_ports FIXED_IO_ps_srstb]
set_property SLEW FAST [get_ports FIXED_IO_ps_srstb]
set_property IOSTANDARD LVCMOS33 [get_ports FIXED_IO_ps_clk]
set_property PACKAGE_PIN B11 [get_ports FIXED_IO_ps_srstb]
set_property PACKAGE_PIN R6 [get_ports DDR_ras_n]
set_property PACKAGE_PIN C9 [get_ports FIXED_IO_ps_porb]
set_property PACKAGE_PIN K3 [get_ports DDR_odt]
set_property PACKAGE_PIN C13 [get_ports {FIXED_IO_mio[31]}]
set_property PACKAGE_PIN A12 [get_ports {FIXED_IO_mio[30]}]
set_property PACKAGE_PIN D13 [get_ports {FIXED_IO_mio[29]}]
set_property PACKAGE_PIN B12 [get_ports {FIXED_IO_mio[28]}]
set_property PACKAGE_PIN D14 [get_ports {FIXED_IO_mio[27]}]
set_property PACKAGE_PIN A13 [get_ports {FIXED_IO_mio[26]}]
set_property PACKAGE_PIN C14 [get_ports {FIXED_IO_mio[25]}]
set_property PACKAGE_PIN B14 [get_ports {FIXED_IO_mio[24]}]
set_property PACKAGE_PIN A14 [get_ports {FIXED_IO_mio[23]}]
set_property PACKAGE_PIN D15 [get_ports {FIXED_IO_mio[22]}]
set_property PACKAGE_PIN C11 [get_ports {FIXED_IO_mio[21]}]
set_property PACKAGE_PIN E15 [get_ports {FIXED_IO_mio[20]}]
set_property PACKAGE_PIN C12 [get_ports {FIXED_IO_mio[19]}]
set_property PACKAGE_PIN B15 [get_ports {FIXED_IO_mio[18]}]
set_property PACKAGE_PIN D11 [get_ports {FIXED_IO_mio[17]}]
set_property PACKAGE_PIN A15 [get_ports {FIXED_IO_mio[16]}]
set_property PACKAGE_PIN D10 [get_ports {FIXED_IO_mio[15]}]
set_property PACKAGE_PIN B9 [get_ports {FIXED_IO_mio[14]}]
set_property PACKAGE_PIN C6 [get_ports {FIXED_IO_mio[13]}]
set_property PACKAGE_PIN B7 [get_ports {FIXED_IO_mio[12]}]
set_property PACKAGE_PIN B10 [get_ports {FIXED_IO_mio[11]}]
set_property PACKAGE_PIN D6 [get_ports {FIXED_IO_mio[10]}]
set_property PACKAGE_PIN B5 [get_ports {FIXED_IO_mio[9]}]
set_property PACKAGE_PIN B6 [get_ports {FIXED_IO_mio[8]}]
set_property PACKAGE_PIN D9 [get_ports {FIXED_IO_mio[7]}]
set_property PACKAGE_PIN A10 [get_ports {FIXED_IO_mio[6]}]
set_property PACKAGE_PIN A9 [get_ports {FIXED_IO_mio[5]}]
set_property PACKAGE_PIN C8 [get_ports {FIXED_IO_mio[4]}]
set_property PACKAGE_PIN A7 [get_ports {FIXED_IO_mio[3]}]
set_property PACKAGE_PIN A8 [get_ports {FIXED_IO_mio[2]}]
set_property PACKAGE_PIN A5 [get_ports {FIXED_IO_mio[1]}]
set_property PACKAGE_PIN D8 [get_ports {FIXED_IO_mio[0]}]
set_property PACKAGE_PIN L4 [get_ports DDR_reset_n]
set_property PACKAGE_PIN R3 [get_ports DDR_we_n]
set_property PACKAGE_PIN J3 [get_ports FIXED_IO_ddr_vrn]
set_property PACKAGE_PIN H3 [get_ports FIXED_IO_ddr_vrp]
set_property PACKAGE_PIN P1 [get_ports {DDR_addr[0]}]
set_property PACKAGE_PIN N1 [get_ports {DDR_addr[1]}]
set_property PACKAGE_PIN M1 [get_ports {DDR_addr[2]}]
set_property PACKAGE_PIN M4 [get_ports {DDR_addr[3]}]
set_property PACKAGE_PIN P3 [get_ports {DDR_addr[4]}]
set_property PACKAGE_PIN P4 [get_ports {DDR_addr[5]}]
set_property PACKAGE_PIN P5 [get_ports {DDR_addr[6]}]
set_property PACKAGE_PIN M5 [get_ports {DDR_addr[7]}]
set_property PACKAGE_PIN P6 [get_ports {DDR_addr[8]}]
set_property PACKAGE_PIN N4 [get_ports {DDR_addr[9]}]
set_property PACKAGE_PIN J1 [get_ports {DDR_addr[10]}]
set_property PACKAGE_PIN L2 [get_ports {DDR_addr[11]}]
set_property PACKAGE_PIN M2 [get_ports {DDR_addr[12]}]
set_property PACKAGE_PIN K1 [get_ports {DDR_addr[14]}]
set_property PACKAGE_PIN K2 [get_ports {DDR_addr[13]}]
set_property PACKAGE_PIN M6 [get_ports {DDR_ba[0]}]
set_property PACKAGE_PIN R1 [get_ports {DDR_ba[1]}]
set_property PACKAGE_PIN N6 [get_ports {DDR_ba[2]}]
set_property PACKAGE_PIN R5 [get_ports DDR_cas_n]
set_property PACKAGE_PIN L3 [get_ports DDR_cke]
set_property PACKAGE_PIN N2 [get_ports DDR_ck_n]
set_property PACKAGE_PIN N3 [get_ports DDR_ck_p]
set_property PACKAGE_PIN C7 [get_ports FIXED_IO_ps_clk]
set_property PACKAGE_PIN R2 [get_ports DDR_cs_n]
set_property PACKAGE_PIN B1 [get_ports {DDR_dm[0]}]
set_property PACKAGE_PIN D3 [get_ports {DDR_dm[1]}]
set_property PACKAGE_PIN D4 [get_ports {DDR_dq[0]}]
set_property PACKAGE_PIN A2 [get_ports {DDR_dq[1]}]
set_property PACKAGE_PIN C4 [get_ports {DDR_dq[2]}]
set_property PACKAGE_PIN C1 [get_ports {DDR_dq[3]}]
set_property PACKAGE_PIN B4 [get_ports {DDR_dq[4]}]
set_property PACKAGE_PIN A4 [get_ports {DDR_dq[5]}]
set_property PACKAGE_PIN C3 [get_ports {DDR_dq[6]}]
set_property PACKAGE_PIN A3 [get_ports {DDR_dq[7]}]
set_property PACKAGE_PIN E1 [get_ports {DDR_dq[8]}]
set_property PACKAGE_PIN D1 [get_ports {DDR_dq[9]}]
set_property PACKAGE_PIN E2 [get_ports {DDR_dq[10]}]
set_property PACKAGE_PIN E3 [get_ports {DDR_dq[11]}]
set_property PACKAGE_PIN F3 [get_ports {DDR_dq[12]}]
set_property PACKAGE_PIN G1 [get_ports {DDR_dq[13]}]
set_property PACKAGE_PIN H1 [get_ports {DDR_dq[14]}]
set_property PACKAGE_PIN H2 [get_ports {DDR_dq[15]}]
set_property PACKAGE_PIN B2 [get_ports {DDR_dqs_n[0]}]
set_property PACKAGE_PIN F2 [get_ports {DDR_dqs_n[1]}]
set_property PACKAGE_PIN C2 [get_ports {DDR_dqs_p[0]}]
set_property PACKAGE_PIN G2 [get_ports {DDR_dqs_p[1]}]
set_property SLEW FAST [get_ports FIXED_IO_ps_clk]



####################################################################################
# Constraints from file : 'OV7670_QVGA_rst_ps7_0_50M_0_board.xdc'
####################################################################################

#--------------------Physical Constraints-----------------



####################################################################################
# Constraints from file : 'OV7670_QVGA_rst_ps7_0_50M_0.xdc'
####################################################################################


# file: OV7670_QVGA_rst_ps7_0_50M_0.xdc
# (c) Copyright 2009 - 2013 Xilinx, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of Xilinx, Inc. and is protected under U.S. and
# international copyright and other intellectual property
# laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# Xilinx, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) Xilinx shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or Xilinx had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# Xilinx products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of Xilinx products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.



####################################################################################
# Constraints from file : 'minized_pins.xdc'
####################################################################################

#######################################################################
# Arduino 8-pin connector
#######################################################################
# To ARD_D0 on Arduino 8-pin  Pin 1
set_property PACKAGE_PIN R8 [get_ports {d_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d_0[0]}]

# To ARD_D1 on Arduino 8-pin  Pin 2
set_property PACKAGE_PIN P8 [get_ports {d_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d_0[1]}]

# To ARD_D2 on Arduino 8-pin  Pin 3
set_property PACKAGE_PIN P9 [get_ports {d_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d_0[2]}]

# To ARD_D3 on Arduino 8-pin  Pin 4
set_property PACKAGE_PIN R7 [get_ports {d_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d_0[3]}]

# To ARD_D4 on Arduino 8-pin  Pin 5
set_property PACKAGE_PIN N7 [get_ports {d_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d_0[4]}]

# To ARD_D5 on Arduino 8-pin  Pin 6
set_property PACKAGE_PIN R10 [get_ports {d_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d_0[5]}]

# To ARD_D6 on Arduino 8-pin  Pin 7
set_property PACKAGE_PIN P10 [get_ports {d_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d_0[6]}]

# To ARD_D7 on Arduino 8-pin  Pin 8
set_property PACKAGE_PIN N8 [get_ports {d_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {d_0[7]}]
#######################################################################
# Arduino 10-pin connector
#######################################################################
# To ARD_D8 on Arduino 10-pin  Pin 1
#set_property PACKAGE_PIN M9 [get_ports ARDUINO_IO1]
#set_property IOSTANDARD LVCMOS33 [get_ports ARDUINO_IO1]

# To ARD_D9 on Arduino 10-pin  Pin 2
#set_property PACKAGE_PIN N9 [get_ports ARDUINO_IO0]
#set_property IOSTANDARD LVCMOS33 [get_ports ARDUINO_IO0]

# To ARD_D10 on Arduino 10-pin  Pin 3
set_property PACKAGE_PIN M10 [get_ports ARDUINO_IO10]
set_property IOSTANDARD LVCMOS33 [get_ports ARDUINO_IO10]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ARDUINO_IO10_IBUF]
# To ARD_D11 on Arduino 10-pin  Pin 4
set_property PACKAGE_PIN M11 [get_ports ARDUINO_IO11]
set_property IOSTANDARD LVCMOS33 [get_ports ARDUINO_IO11]

# To ARD_D12 on Arduino 10-pin  Pin 5
set_property PACKAGE_PIN R11 [get_ports ARDUINO_IO12]
set_property IOSTANDARD LVCMOS33 [get_ports ARDUINO_IO12]

# To ARD_D13 on Arduino 10-pin  Pin 6
set_property PACKAGE_PIN P11 [get_ports ARDUINO_IO13]
set_property IOSTANDARD LVCMOS33 [get_ports ARDUINO_IO13]

#######################################################################
# Arduino 6-pin connector
#######################################################################
# To ARD_A0 on Arduino 6-pin  Pin 6
set_property PACKAGE_PIN F14 [get_ports ARDUINO_A0]
set_property IOSTANDARD LVCMOS33 [get_ports ARDUINO_A0]

# To ARD_A1 on Arduino 6-pin  Pin 5
set_property PACKAGE_PIN F13 [get_ports ARDUINO_A1]
set_property IOSTANDARD LVCMOS33 [get_ports ARDUINO_A1]

# To ARD_A2 on Arduino 6-pin  Pin 4
#set_property PACKAGE_PIN F12 [get_ports ARD_ADDR2]
#set_property IOSTANDARD LVCMOS33 [get_ports ARD_ADDR2]

# To ARD_A3 on Arduino 6-pin  Pin 3 (and PL_LED Green)
#set_property PACKAGE_PIN E13 [get_ports ARD_ADDR3]
#set_property IOSTANDARD LVCMOS33 [get_ports ARD_ADDR3]
#set_property PACKAGE_PIN E13 [get_ports pl_led_g]
#set_property IOSTANDARD LVCMOS33 [get_ports pl_led_g]

# To ARD_A4 on Arduino 6-pin  Pin 2 (and PL_LED Red)
#set_property PACKAGE_PIN E12 [get_ports ARD_ADDR4]
#set_property IOSTANDARD LVCMOS33 [get_ports ARD_ADDR4]
set_property PACKAGE_PIN E12 [get_ports PL_LED_R]
set_property IOSTANDARD LVCMOS33 [get_ports PL_LED_R]

# To ARD_A5 on Arduino 6-pin  Pin 1 (and PL_SW)
#set_property PACKAGE_PIN E11 [get_ports ARD_ADDR5]
#set_property IOSTANDARD LVCMOS33 [get_ports ARD_ADDR5]
set_property PACKAGE_PIN E11 [get_ports PL_SW]
set_property IOSTANDARD LVCMOS33 [get_ports PL_SW]

#######################################################################
# I2C
#######################################################################
# To SDA on Arduino 10-pin  Pin 9 and Motion Sensor
#set_property PACKAGE_PIN F15 [get_ports I2C_SDA]
#set_property IOSTANDARD LVCMOS33 [get_ports I2C_SDA]
set_property PACKAGE_PIN F15 [get_ports I2C_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports I2C_SDA]

# To SCL on Arduino 10-pin  Pin 10 and Motion Sensor
#set_property PACKAGE_PIN G15 [get_ports I2C_SCL]
#set_property IOSTANDARD LVCMOS33 [get_ports I2C_SCL]
set_property PACKAGE_PIN G15 [get_ports I2C_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports I2C_SCL]

#######################################################################
# Pmod #1
#######################################################################
set_property PACKAGE_PIN L15 [get_ports {VGA_R[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[0]}]

set_property PACKAGE_PIN M15 [get_ports {VGA_R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[1]}]

set_property PACKAGE_PIN L14 [get_ports {VGA_R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[2]}]

set_property PACKAGE_PIN M14 [get_ports {VGA_R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[3]}]

set_property PACKAGE_PIN K13 [get_ports {VGA_B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[0]}]

set_property PACKAGE_PIN L13 [get_ports {VGA_B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[1]}]

set_property PACKAGE_PIN N13 [get_ports {VGA_B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[2]}]

set_property PACKAGE_PIN N14 [get_ports {VGA_B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[3]}]

#######################################################################
# Pmod #2
#######################################################################
set_property PACKAGE_PIN P13 [get_ports {VGA_G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[0]}]

set_property PACKAGE_PIN P14 [get_ports {VGA_G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[1]}]

set_property PACKAGE_PIN N11 [get_ports {VGA_G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[2]}]

set_property PACKAGE_PIN N12 [get_ports {VGA_G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[3]}]

set_property PACKAGE_PIN P15 [get_ports VGA_HS]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_HS]

set_property PACKAGE_PIN R15 [get_ports VGA_VS]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_VS]

#set_property PACKAGE_PIN R12 [get_ports PMOD2_PIN9]
#set_property IOSTANDARD LVCMOS33 [get_ports PMOD2_PIN9]

#set_property PACKAGE_PIN R13 [get_ports PMOD2_PIN10]
#set_property IOSTANDARD LVCMOS33 [get_ports PMOD2_PIN10]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ARDUINO_IO10_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ARDUINO_IO10_IBUF_BUFG]


create_clock -period 40.000 -name clockOv7670In -waveform {0.000 20.000} [get_ports ARDUINO_IO10]


set_property PULLUP true [get_ports I2C_SCL]
set_property PULLUP true [get_ports I2C_SDA]


# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
