# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/ip/Z_system_processing_system7_0_0/Z_system_processing_system7_0_0.xci
# IP: The module: 'Z_system_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/ip/Z_system_processing_system7_0_0/Z_system_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Z_system_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/ip/Z_system_processing_system7_0_0/Z_system_processing_system7_0_0.xci
# IP: The module: 'Z_system_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/ip/Z_system_processing_system7_0_0/Z_system_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Z_system_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
