set_property SRC_FILE_INFO {cfile:f:/Git_Fpga/FPGA_Starter/Project/LiveCamera/LiveCamera.srcs/sources_1/bd/OV7670_QVGA/ip/OV7670_QVGA_clk_wiz_0_0/OV7670_QVGA_clk_wiz_0_0.xdc rfile:../LiveCamera.srcs/sources_1/bd/OV7670_QVGA/ip/OV7670_QVGA_clk_wiz_0_0/OV7670_QVGA_clk_wiz_0_0.xdc id:1 order:EARLY scoped_inst:OV7670_QVGA_i/clk_wiz_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:f:/Git_Fpga/FPGA_Starter/Project/LiveCamera/LiveCamera.srcs/sources_1/bd/OV7670_QVGA/ip/OV7670_QVGA_processing_system7_0_0/OV7670_QVGA_processing_system7_0_0.xdc rfile:../LiveCamera.srcs/sources_1/bd/OV7670_QVGA/ip/OV7670_QVGA_processing_system7_0_0/OV7670_QVGA_processing_system7_0_0.xdc id:2 order:EARLY scoped_inst:OV7670_QVGA_i/processing_system7_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:F:/Git_Fpga/FPGA_Starter/Project/LiveCamera/LiveCamera.srcs/constrs_1/imports/Fpga/minized_pins.xdc rfile:../LiveCamera.srcs/constrs_1/imports/Fpga/minized_pins.xdc id:3} [current_design]
current_instance OV7670_QVGA_i/clk_wiz_0/inst
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.1
current_instance
current_instance OV7670_QVGA_i/processing_system7_0/inst
set_property src_info {type:SCOPED_XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.6
set_property src_info {type:SCOPED_XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_1 0.3
current_instance
set_property src_info {type:XDC file:3 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P9 [get_ports ARD_DAT2]
set_property src_info {type:XDC file:3 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ARD_DAT2]
set_property src_info {type:XDC file:3 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R7 [get_ports ARD_DAT3]
set_property src_info {type:XDC file:3 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ARD_DAT3]
set_property src_info {type:XDC file:3 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N7 [get_ports ARD_DAT4]
set_property src_info {type:XDC file:3 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ARD_DAT4]
set_property src_info {type:XDC file:3 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R10 [get_ports ARD_DAT5]
set_property src_info {type:XDC file:3 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ARD_DAT5]
set_property src_info {type:XDC file:3 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P10 [get_ports ARD_DAT6]
set_property src_info {type:XDC file:3 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ARD_DAT6]
set_property src_info {type:XDC file:3 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N8 [get_ports ARD_DAT7]
set_property src_info {type:XDC file:3 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ARD_DAT7]
set_property src_info {type:XDC file:3 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M9 [get_ports ARD_DAT8]
set_property src_info {type:XDC file:3 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ARD_DAT8]
set_property src_info {type:XDC file:3 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N9 [get_ports ARD_DAT9]
set_property src_info {type:XDC file:3 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ARD_DAT9]
set_property src_info {type:XDC file:3 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F12 [get_ports ARD_ADDR2]
set_property src_info {type:XDC file:3 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ARD_ADDR2]
set_property src_info {type:XDC file:3 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E13 [get_ports pl_led_g]
set_property src_info {type:XDC file:3 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports pl_led_g]
set_property src_info {type:XDC file:3 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports PMOD1_PIN1]
set_property src_info {type:XDC file:3 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PMOD1_PIN1]
set_property src_info {type:XDC file:3 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports PMOD1_PIN2]
set_property src_info {type:XDC file:3 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PMOD1_PIN2]
set_property src_info {type:XDC file:3 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L14 [get_ports PMOD1_PIN3]
set_property src_info {type:XDC file:3 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PMOD1_PIN3]
set_property src_info {type:XDC file:3 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports PMOD1_PIN4]
set_property src_info {type:XDC file:3 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PMOD1_PIN4]
set_property src_info {type:XDC file:3 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K13 [get_ports PMOD1_PIN7]
set_property src_info {type:XDC file:3 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PMOD1_PIN7]
set_property src_info {type:XDC file:3 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L13 [get_ports PMOD1_PIN8]
set_property src_info {type:XDC file:3 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PMOD1_PIN8]
set_property src_info {type:XDC file:3 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N13 [get_ports PMOD1_PIN9]
set_property src_info {type:XDC file:3 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PMOD1_PIN9]
set_property src_info {type:XDC file:3 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N14 [get_ports PMOD1_PIN10]
set_property src_info {type:XDC file:3 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PMOD1_PIN10]
set_property src_info {type:XDC file:3 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P13 [get_ports PMOD2_PIN1]
set_property src_info {type:XDC file:3 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PMOD2_PIN1]
set_property src_info {type:XDC file:3 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P14 [get_ports PMOD2_PIN2]
set_property src_info {type:XDC file:3 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PMOD2_PIN2]
set_property src_info {type:XDC file:3 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N11 [get_ports PMOD2_PIN3]
set_property src_info {type:XDC file:3 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PMOD2_PIN3]
set_property src_info {type:XDC file:3 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N12 [get_ports PMOD2_PIN4]
set_property src_info {type:XDC file:3 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PMOD2_PIN4]
set_property src_info {type:XDC file:3 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P15 [get_ports PMOD2_PIN7]
set_property src_info {type:XDC file:3 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PMOD2_PIN7]
set_property src_info {type:XDC file:3 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R15 [get_ports PMOD2_PIN8]
set_property src_info {type:XDC file:3 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PMOD2_PIN8]
set_property src_info {type:XDC file:3 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R12 [get_ports PMOD2_PIN9]
set_property src_info {type:XDC file:3 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PMOD2_PIN9]
set_property src_info {type:XDC file:3 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R13 [get_ports PMOD2_PIN10]
set_property src_info {type:XDC file:3 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PMOD2_PIN10]
