# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Z_system/Z_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system || ORIG_REF_NAME==Z_system}]

# IP: bd/Z_system/ip/Z_system_processing_system7_0_0/Z_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_processing_system7_0_0 || ORIG_REF_NAME==Z_system_processing_system7_0_0}]

# IP: bd/Z_system/ip/Z_system_axi_bram_ctrl_0_0/Z_system_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_axi_bram_ctrl_0_0 || ORIG_REF_NAME==Z_system_axi_bram_ctrl_0_0}]

# IP: bd/Z_system/ip/Z_system_axi_bram_ctrl_0_bram_0/Z_system_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==Z_system_axi_bram_ctrl_0_bram_0}]

# IP: bd/Z_system/ip/Z_system_axi_mem_intercon_0/Z_system_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_axi_mem_intercon_0 || ORIG_REF_NAME==Z_system_axi_mem_intercon_0}]

# IP: bd/Z_system/ip/Z_system_rst_ps7_0_50M_0/Z_system_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_rst_ps7_0_50M_0 || ORIG_REF_NAME==Z_system_rst_ps7_0_50M_0}]

# IP: bd/Z_system/ip/Z_system_PWM_w_Int_0_0/Z_system_PWM_w_Int_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_PWM_w_Int_0_0 || ORIG_REF_NAME==Z_system_PWM_w_Int_0_0}]

# IP: bd/Z_system/ip/Z_system_ila_0_0/Z_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_ila_0_0 || ORIG_REF_NAME==Z_system_ila_0_0}]

# IP: bd/Z_system/ip/Z_system_jtag_axi_0_0/Z_system_jtag_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_jtag_axi_0_0 || ORIG_REF_NAME==Z_system_jtag_axi_0_0}]

# IP: bd/Z_system/ip/Z_system_xbar_0/Z_system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_xbar_0 || ORIG_REF_NAME==Z_system_xbar_0}]

# IP: bd/Z_system/ip/Z_system_auto_ds_0/Z_system_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_auto_ds_0 || ORIG_REF_NAME==Z_system_auto_ds_0}]

# IP: bd/Z_system/ip/Z_system_auto_pc_0/Z_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_auto_pc_0 || ORIG_REF_NAME==Z_system_auto_pc_0}]

# IP: bd/Z_system/ip/Z_system_auto_us_1/Z_system_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_auto_us_1 || ORIG_REF_NAME==Z_system_auto_us_1}]

# IP: bd/Z_system/ip/Z_system_auto_pc_1/Z_system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_auto_pc_1 || ORIG_REF_NAME==Z_system_auto_pc_1}]

# IP: bd/Z_system/ip/Z_system_auto_us_0/Z_system_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Z_system_auto_us_0 || ORIG_REF_NAME==Z_system_auto_us_0}]

# XDC: bd/Z_system/Z_system_ooc.xdc
