# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z007sclg225-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.cache/wt [current_project]
set_property parent.project_path C:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths c:/Speedway/ZynqHW/2017_1/ip_repo/PWM_w_Int_1.0 [current_project]
set_property ip_output_repo c:/Speedway/ZynqHW/2017_1/Temp/ZynqDesign/ZynqDesign.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/hdl/Z_system_wrapper.vhd
add_files C:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/Z_system.bd
set_property used_in_implementation false [get_files -all c:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/ip/Z_system_processing_system7_0_0/Z_system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/ip/Z_system_axi_bram_ctrl_0_0/Z_system_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/ip/Z_system_axi_bram_ctrl_0_bram_0/Z_system_axi_bram_ctrl_0_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/ip/Z_system_rst_ps7_0_50M_0/Z_system_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/ip/Z_system_rst_ps7_0_50M_0/Z_system_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/ip/Z_system_rst_ps7_0_50M_0/Z_system_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/ip/Z_system_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/ip/Z_system_ila_0_0/Z_system_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/ip/Z_system_jtag_axi_0_0/constraints/jtag_axi.xdc]
set_property used_in_implementation false [get_files -all c:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/ip/Z_system_jtag_axi_0_0/Z_system_jtag_axi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/ip/Z_system_xbar_0/Z_system_xbar_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/ip/Z_system_auto_ds_0/Z_system_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/ip/Z_system_auto_ds_0/Z_system_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/ip/Z_system_auto_ds_0/Z_system_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/ip/Z_system_auto_pc_0/Z_system_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_1/Z_system_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_1/Z_system_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_1/Z_system_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/ip/Z_system_auto_pc_1/Z_system_auto_pc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_0/Z_system_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_0/Z_system_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/ip/Z_system_auto_us_0/Z_system_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/Z_system_ooc.xdc]
set_property is_locked true [get_files C:/Speedway/ZynqHW/2017_1/ZynqDesign/ZynqDesign.srcs/sources_1/bd/Z_system/Z_system.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Z_system_wrapper -part xc7z007sclg225-1


write_checkpoint -force -noxdef Z_system_wrapper.dcp

catch { report_utilization -file Z_system_wrapper_utilization_synth.rpt -pb Z_system_wrapper_utilization_synth.pb }
