# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/Demo/Demo.srcs/sources_1/bd/Demo/ip/Demo_rst_ps7_0_50M_2/Demo_rst_ps7_0_50M_2.xci
# IP: The module: 'Demo_rst_ps7_0_50M_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Demo/Demo.srcs/sources_1/bd/Demo/ip/Demo_rst_ps7_0_50M_2/Demo_rst_ps7_0_50M_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Demo_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Demo/Demo.srcs/sources_1/bd/Demo/ip/Demo_rst_ps7_0_50M_2/Demo_rst_ps7_0_50M_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'Demo_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Demo/Demo.srcs/sources_1/bd/Demo/ip/Demo_rst_ps7_0_50M_2/Demo_rst_ps7_0_50M_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Demo_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: F:/Demo/Demo.srcs/sources_1/bd/Demo/ip/Demo_rst_ps7_0_50M_2/Demo_rst_ps7_0_50M_2.xci
# IP: The module: 'Demo_rst_ps7_0_50M_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Demo/Demo.srcs/sources_1/bd/Demo/ip/Demo_rst_ps7_0_50M_2/Demo_rst_ps7_0_50M_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Demo_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Demo/Demo.srcs/sources_1/bd/Demo/ip/Demo_rst_ps7_0_50M_2/Demo_rst_ps7_0_50M_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'Demo_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Demo/Demo.srcs/sources_1/bd/Demo/ip/Demo_rst_ps7_0_50M_2/Demo_rst_ps7_0_50M_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Demo_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
