vlib work
vlib activehdl

vlib activehdl/xil_defaultlib
vlib activehdl/xpm
vlib activehdl/axi_infrastructure_v1_1_0
vlib activehdl/xil_common_vip_v1_0_0
vlib activehdl/smartconnect_v1_0
vlib activehdl/axi_protocol_checker_v1_1_13
vlib activehdl/axi_vip_v1_0_1
vlib activehdl/blk_mem_gen_v8_3_6
vlib activehdl/axi_bram_ctrl_v4_0_11
vlib activehdl/lib_cdc_v1_0_2
vlib activehdl/proc_sys_reset_v5_0_11
vlib activehdl/jtag_axi
vlib activehdl/generic_baseblocks_v2_1_0
vlib activehdl/axi_register_slice_v2_1_12
vlib activehdl/fifo_generator_v13_1_4
vlib activehdl/axi_data_fifo_v2_1_11
vlib activehdl/axi_crossbar_v2_1_13
vlib activehdl/axi_protocol_converter_v2_1_12
vlib activehdl/axi_clock_converter_v2_1_11
vlib activehdl/axi_dwidth_converter_v2_1_12

vmap xil_defaultlib activehdl/xil_defaultlib
vmap xpm activehdl/xpm
vmap axi_infrastructure_v1_1_0 activehdl/axi_infrastructure_v1_1_0
vmap xil_common_vip_v1_0_0 activehdl/xil_common_vip_v1_0_0
vmap smartconnect_v1_0 activehdl/smartconnect_v1_0
vmap axi_protocol_checker_v1_1_13 activehdl/axi_protocol_checker_v1_1_13
vmap axi_vip_v1_0_1 activehdl/axi_vip_v1_0_1
vmap blk_mem_gen_v8_3_6 activehdl/blk_mem_gen_v8_3_6
vmap axi_bram_ctrl_v4_0_11 activehdl/axi_bram_ctrl_v4_0_11
vmap lib_cdc_v1_0_2 activehdl/lib_cdc_v1_0_2
vmap proc_sys_reset_v5_0_11 activehdl/proc_sys_reset_v5_0_11
vmap jtag_axi activehdl/jtag_axi
vmap generic_baseblocks_v2_1_0 activehdl/generic_baseblocks_v2_1_0
vmap axi_register_slice_v2_1_12 activehdl/axi_register_slice_v2_1_12
vmap fifo_generator_v13_1_4 activehdl/fifo_generator_v13_1_4
vmap axi_data_fifo_v2_1_11 activehdl/axi_data_fifo_v2_1_11
vmap axi_crossbar_v2_1_13 activehdl/axi_crossbar_v2_1_13
vmap axi_protocol_converter_v2_1_12 activehdl/axi_protocol_converter_v2_1_12
vmap axi_clock_converter_v2_1_11 activehdl/axi_clock_converter_v2_1_11
vmap axi_dwidth_converter_v2_1_12 activehdl/axi_dwidth_converter_v2_1_12

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" \
"C:/Xilinx/Vivado/2017.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"C:/Xilinx/Vivado/2017.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93 \
"C:/Xilinx/Vivado/2017.1/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work axi_infrastructure_v1_1_0  -v2k5 "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" \
"../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work xil_common_vip_v1_0_0  -sv2k12 "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" \
"../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl/xil_common_vip_v1_0_vl_rfs.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" \
"../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/sc_util_v1_0_vl_rfs.sv" \

vlog -work axi_protocol_checker_v1_1_13  -sv2k12 "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" \
"../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8017/hdl/axi_protocol_checker_v1_1_vl_rfs.sv" \

vlog -work axi_vip_v1_0_1  -sv2k12 "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" \
"../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl/axi_vip_v1_0_vl_rfs.sv" \
"../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" \
"../../../bd/Z_system/ip/Z_system_processing_system7_0_0/sim/Z_system_processing_system7_0_0.v" \

vlog -work blk_mem_gen_v8_3_6  -v2k5 "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" \
"../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/4158/simulation/blk_mem_gen_v8_3.v" \

vcom -work axi_bram_ctrl_v4_0_11 -93 \
"../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/9183/hdl/axi_bram_ctrl_v4_0_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../bd/Z_system/ip/Z_system_axi_bram_ctrl_0_0/sim/Z_system_axi_bram_ctrl_0_0.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" \
"../../../bd/Z_system/ip/Z_system_axi_bram_ctrl_0_bram_0/sim/Z_system_axi_bram_ctrl_0_bram_0.v" \

vcom -work lib_cdc_v1_0_2 -93 \
"../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/52cb/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work proc_sys_reset_v5_0_11 -93 \
"../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/5db7/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../bd/Z_system/ip/Z_system_rst_ps7_0_50M_0/sim/Z_system_rst_ps7_0_50M_0.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" \
"../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/73b3/hdl/PWM_Controller_Int.v" \

vcom -work xil_defaultlib -93 \
"../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/73b3/hdl/PWM_w_Int_v1_0.vhd" \
"../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/73b3/hdl/PWM_w_Int_v1_0_S00_AXI.vhd" \
"../../../bd/Z_system/ip/Z_system_PWM_w_Int_0_0/sim/Z_system_PWM_w_Int_0_0.vhd" \
"../../../bd/Z_system/ip/Z_system_ila_0_0/sim/Z_system_ila_0_0.vhd" \

vlog -work jtag_axi  -v2k5 "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" \
"../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/08da/hdl/jtag_axi_v1_2_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" \
"../../../bd/Z_system/ip/Z_system_jtag_axi_0_0/sim/Z_system_jtag_axi_0_0.v" \

vlog -work generic_baseblocks_v2_1_0  -v2k5 "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" \
"../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9c1/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_12  -v2k5 "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" \
"../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e33/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work fifo_generator_v13_1_4  -v2k5 "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" \
"../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/ebc2/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_1_4 -93 \
"../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/ebc2/hdl/fifo_generator_v13_1_rfs.vhd" \

vlog -work fifo_generator_v13_1_4  -v2k5 "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" \
"../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/ebc2/hdl/fifo_generator_v13_1_rfs.v" \

vlog -work axi_data_fifo_v2_1_11  -v2k5 "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" \
"../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/5235/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_crossbar_v2_1_13  -v2k5 "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" \
"../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/78eb/hdl/axi_crossbar_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" \
"../../../bd/Z_system/ip/Z_system_xbar_0/sim/Z_system_xbar_0.v" \

vlog -work axi_protocol_converter_v2_1_12  -v2k5 "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" \
"../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/138d/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work axi_clock_converter_v2_1_11  -v2k5 "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" \
"../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/c526/hdl/axi_clock_converter_v2_1_vl_rfs.v" \

vlog -work axi_dwidth_converter_v2_1_12  -v2k5 "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" \
"../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/fef9/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/7e3a/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/2ad9/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/16a2/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/856d/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d5eb/hdl" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/d618/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/f9cc/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/8323/hdl/verilog" "+incdir+../../../../ZynqDesign.srcs/sources_1/bd/Z_system/ipshared/0e4e/hdl/verilog" \
"../../../bd/Z_system/ip/Z_system_auto_ds_0/sim/Z_system_auto_ds_0.v" \
"../../../bd/Z_system/ip/Z_system_auto_pc_0/sim/Z_system_auto_pc_0.v" \
"../../../bd/Z_system/ip/Z_system_auto_us_1/sim/Z_system_auto_us_1.v" \
"../../../bd/Z_system/ip/Z_system_auto_pc_1/sim/Z_system_auto_pc_1.v" \
"../../../bd/Z_system/ip/Z_system_auto_us_0/sim/Z_system_auto_us_0.v" \

vcom -work xil_defaultlib -93 \
"../../../bd/Z_system/hdl/Z_system.vhd" \

vlog -work xil_defaultlib \
"glbl.v"

